Resources:
  EKSNodegroup:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      ClusterName: plsawsd-signe-eks-uat-cluster
      NodegroupName: plsawsd-signe-uat-node-group
      NodeRole: 'arn:aws:iam::085664843119:role/plsawsd-signe-uat-eksmngnodegroup-role'
      CapacityType: ON_DEMAND
      UpdateConfig:
        MaxUnavailable: '1'
      InstanceTypes:
        - t3.medium
      LaunchTemplate:
        Name: worker-node-lt-launch-template
        Version: '1'
      ScalingConfig:
        MinSize: 2
        DesiredSize: 2
        MaxSize: 4
      Labels:
        env: uat
      Subnets:
        - subnet-09ef16e6401b4674d
        - subnet-056513415ce2ca674

