AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Create an ElasticCache Replication Group with Multi-AZ.
Parameters:
  CacheNodeType:
    Description: The instance type the nodes will launch under.
    Type: String
    Default: cache.m6g.large
    AllowedValues:
      - cache.m6g.large
      - cache.r6g.large
      - cache.t3.micro
  MultiAZSupport:
    Description: >-
      Indicates whether Multi-AZ is enabled. When Multi-AZ is enabled, a
      read-only replica is automatically promoted to a read-write primary
      cluster if the existing primary cluster fails. If you specify true, you
      must specify a value greater than 1 for the NumCacheClusters property.
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
  NumCacheClusters:
    Description: >-
      If MultiAZ support is enabled, you must specify a value greater than 1.
    Default: '1'
    Type: Number
    MinValue: '1'
    MaxValue: '6'
  RedisPort:
    Description: >-
      The port number on which each member of the replication group accepts connections.
    Type: Number
    Default: '6379'
  ReplicationGroupDescription:
    Description: Enter Your replication group.
    Type: String
    Default: 'pace20-sso-redis-prod-eu'
  ClusterName:
    Description: Enter ElastiCache Cluster name.
    Type: String
  VpcId:
    Description: Select the VPC to create this ReplicationGroup under
    Type: 'AWS::EC2::VPC::Id'
  CidrIp:
    Description: The CIDR you want to access to the Replication Group
    Type: String
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    MinLength: '9'
    MaxLength: '18'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x
  SnapshotRetentionLimit:
    Description: >-
      The number of days that ElastiCache retains automatic snapshots before deleting them.
    Type: Number
    Default: '7'
  SnapshotWindow:
    Description: >-
      The time range (in UTC) when ElastiCache takes a daily snapshot of your node group.
    Type: String
    Default: '05:00-09:00'
    AllowedPattern: '\d{2}:\d{2}-\d{2}:\d{2}'
    ConstraintDescription: 'must be a valid timestamp range, for example 05:00-09:00'
  PreferredMaintenanceWindow:
    Description: >-
      The weekly time range during which system maintenance can occur. Use the
      following format to specify a time range: ddd:hh24:mi-ddd:hh24:mi (24H
      Clock UTC).
    Type: String
    Default: 'sun:22:00-sun:23:30'
    AllowedPattern: >-
      (mon|tue|wed|thu|fri|sat|sun):\d{2}:\d{2}-(mon|tue|wed|thu|fri|sat|sun):\d{2}:\d{2}
    ConstraintDescription: >-
      must be a valid timestamp range with day of week, for example
      sun:22:00-sun:23:30
  SubnetA:
    Description: >-
      One of the subnets you would like the ReplicationGroup to be created in.
      In this example we only accept 2 subnets
    Type: 'AWS::EC2::Subnet::Id'
  SubnetB:
    Description: >-
      One of the subnets you would like the ReplicationGroup to be created in.
      In this example we only accept 2 subnets
    Type: 'AWS::EC2::Subnet::Id'
Resources:
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security Group for Example Replication Group
      SecurityGroupIngress:
        - CidrIp: !Ref CidrIp
          FromPort: !Ref RedisPort
          ToPort: !Ref RedisPort
          IpProtocol: tcp
      VpcId: !Ref VpcId
  SubnetGroup:
    Type: 'AWS::ElastiCache::SubnetGroup'
    Properties:
      Description: Subnet Group for Example Replication Group
      SubnetIds:
        - !Ref SubnetA
        - !Ref SubnetB
  ReplicationGroup:
    Type: 'AWS::ElastiCache::ReplicationGroup'
    Properties:
      ClusterName: !Ref ClusterName
      AutomaticFailoverEnabled: !Ref MultiAZSupport
      CacheNodeType: !Ref CacheNodeType
      CacheSubnetGroupName: !Ref SubnetGroup
      Engine: redis
      NumCacheClusters: !Ref NumCacheClusters
      Port: !Ref RedisPort
      PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindow
      ReplicationGroupDescription: !Ref ReplicationGroupDescription
      SecurityGroupIds:
        - !GetAtt 
          - SecurityGroup
          - GroupId
      SnapshotRetentionLimit: !Ref SnapshotRetentionLimit
      SnapshotWindow: !Ref SnapshotWindow
      Tags: 
            - Key: Cluster name
              Value: "pace20-sso-redis-prod-eu"
            - Key: Name
              Value: "pace20-sso-redis-prod-eu"
Outputs:
  RGEndpoint:
    Description: The primary endpoint location
    Value: !Join 
      - ''
      - - 'redis://'
        - !GetAtt 
          - ReplicationGroup
          - PrimaryEndPoint.Address
        - ':'
        - !GetAtt 
          - ReplicationGroup
          - PrimaryEndPoint.Port
