AWSTemplateFormatVersion: 2010-09-09
Description: trainman-eks-client-server.
Parameters:
  VpcId:
    Description: Select your VPC Id.
    Type: 'AWS::EC2::VPC::Id'
    Default: ''
  SubnetId1:
    Description: Select your Subnet Id.
    Type: 'AWS::EC2::Subnet::Id'
    Default: ''
  SshServerKeyName:
    Description: Name of an existing EC2 KeyPair to Prod Server.
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.
  InstanceAMIId:
    Description: Type the base Ami Id.
    Type: String
    Default: 'ami-0e67cac586a5b900a'
  InstanceType:
    Description: Type the instance.
    Type: String
    Default: ''
  InstanceSecurityGroupID:
    Description: Enter your security Group ID.
    Type: String
    Default: ''
  Environmentname:
    Description: Enter the Environmentname.
    Type: String
    Default: '' 
  Ec2RootVolumeSize:
    Description: RootVolumeSize minimum value in GB.
    Type: Number
    Default: 8
  EC2InstanceName:
    Description: Enter the Name of the Instance.
    Default: ''
    Type: String
  EC2InstanceRole:
    Description: Enter the Role Name.
    Type: String
    Default: 'salespanda-preprod-web-server-role'

Resources:
  Ec2InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref EC2InstanceRole

  EC2Ec2Instance1:
    Type: 'AWS::EC2::Instance'
    Properties:
      #DisableApiTermination: 'True'
      InstanceInitiatedShutdownBehavior: stop
      ImageId: !Ref InstanceAMIId
      SecurityGroupIds: 
       - sg-05348409c8d2721e5
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref Ec2InstanceProfile
      KeyName: !Ref SshServerKeyName
      Monitoring: 'false'
      Tags:
        - Key: Name
          Value: !Ref 'AWS::StackName'
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            DeleteOnTermination: 'true'
            VolumeSize: !Ref Ec2RootVolumeSize
            Encrypted: 'true'
            VolumeType: "gp3"
            
      Tags:
        - Key: Name
          Value: !Ref EC2InstanceName
        - Key: environment
          Value: !Ref Environmentname
