apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"fluentd","namespace":"amazon-cloudwatch"}}
  name: fluentd
  namespace: amazon-cloudwatch
secrets:
- name: fluentd-token-jdxrv