Description: Pipeline to Deploy Code from S3 to Server
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  CodePipelineName:
    Description: The name of the server 
    Type: String
    Default: SP-Prod-Pipeline-React
  ServerName:
    Description: The name of the server 
    Type: String
    Default: SALESPANDA-PREPROD-APP-SERVER-1A
  EnvironmentName:
    Description: The Current working Environment 
    Type: String
  SourceBucket:
    Description: Enter the CodeCommit Repsitory Name  
    Type: String
    Default: salespanda-gitlab-s3
  SourceObjectKey:
    Description: Enter the Name of the branch 
    Type: String
    Default: Preprod-Server/code.zip
  Artifactbucket:
    Description: The name of the artifact bucket 
    Type: String
    Default: codepipeline-ap-south-1-637795064357
  ApplicationName:
    Description: Name of the application to be deployed
    Type: String
    Default: Preprod-Server-Deployment
  ComputePlatform:
    Description: The type of platform where the application is  to be deployed
    Type: String
    Default: Server
  DeploymentGroupName:
    Description: name of the deployment group to be used.
    Type: String
    Default: Preprod-Server-Deploymentgroup
  DeployConfiguration:
    Description: Select the Deployment configuration for codedeploy
    Type: String
    AllowedValues:
    - CodeDeployDefault.OneAtATime
    - CodeDeployDefault.HalfAtATime
    - CodeDeployDefault.AllAtOnce
  TriggerName:
    Description: The name of the notification trigger about deployment or instance events.
    Type: String
  CodePipelineSNSarn:
    Description: Enter the SNS Topic ARN to send the notifications for CICD.
    Type: String
    Default: arn:aws:sns:ap-south-1:013297583948:Pipeline-Notifications
  TagKey:
    Type: String
    Default: Name
    Description: The tag name that is associated with EC2 instances on which CodeDeploy
      agent is installed
  TagValue:
    Type: String
    Description: The value associated with TagKey
  SourceOutputArtifacts:
    Type: String
    Description: Name of the Source OutputArtifacts generated by the soucre stage of pipeline.
Resources:
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codepipeline.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: codepipeline-service
        PolicyDocument:
          Statement:
          - Action:
            - codecommit:GetBranch
            - codecommit:GetCommit
            - codecommit:UploadArchive
            - codecommit:GetUploadArchiveStatus
            - codecommit:CancelUploadArchive
            - codebuild:*
            Resource: "*"
            Effect: Allow
          - Action:
            - s3:GetObject
            - s3:GetObjectVersion
            - s3:GetBucketVersioning
            Resource: "*"
            Effect: Allow
          - Action:
            - s3:PutObject
            Resource:
            - arn:aws:s3:::codepipeline*
            Effect: Allow
          - Action:
            - codedeploy:CreateDeployment
            - codedeploy:GetApplicationRevision
            - codedeploy:GetDeployment
            - codedeploy:GetDeploymentConfig
            - codedeploy:RegisterApplicationRevision
            Resource: "*"
            Effect: Allow
          - Action:
            - ec2:*
            - elasticloadbalancing:*
            - autoscaling:*
            - cloudwatch:*
            - s3:*
            - sns:*
            - cloudformation:*
            - rds:*
            - sqs:*
            - ecs:*
            - iam:PassRole
            Resource: "*"
            Effect: Allow
          - Action:
            - lambda:InvokeFunction
            - lambda:ListFunctions
            Resource: "*"
            Effect: Allow
          Version: '2012-10-17'
  CodeDeployServiceIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: CodeDeployTrustPolicy
          Effect: Allow
          Principal:
            Service:
            - codedeploy.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole
  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName:
        Ref: ApplicationName
      ComputePlatform:
        Ref: ComputePlatform
      Tags:
      - Key: ApplicationName
        Value:
          Ref: ApplicationName
      - Key: ComputePlatform
        Value:
          Ref: ComputePlatform
      - Key: Project
        Value: salespanda
      - Key: createdBy
        Value: uipl
      - Key: Environment
        Value: preprod
  CodeDeployDeploymentGroup:
    DependsOn:
    - CodeDeployApplication
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      DeploymentGroupName:
        Ref: DeploymentGroupName
      ApplicationName:
        Ref: CodeDeployApplication
      DeploymentConfigName:
        Ref: DeployConfiguration

      ServiceRoleArn:
        Fn::GetAtt:
        - CodeDeployServiceIAMRole
        - Arn
      AutoRollbackConfiguration:
        Enabled: 'true'
        Events:
        - DEPLOYMENT_FAILURE
      TriggerConfigurations:
      - TriggerEvents:
        - DeploymentSuccess
        - DeploymentRollback
        TriggerName:
          Ref: TriggerName
        TriggerTargetArn:
          Ref: CodePipelineSNSarn
  CodePipelineStack:
    Type: AWS::CodePipeline::Pipeline
    DependsOn: CodeDeployDeploymentGroup
    Properties:
      Name: !Ref CodePipelineName
      RoleArn:
        Fn::Join:
        - ''
        - - 'arn:aws:iam::'
          - Ref: AWS::AccountId
          - ":role/"
          - Ref: CodePipelineRole
      Stages:
      - Name: Source
        Actions:
        - InputArtifacts: []
          Name: Source
          ActionTypeId:
            Category: Source
            Owner: AWS
            Version: '1'
            Provider: S3
          OutputArtifacts:
          - Name: !Ref SourceOutputArtifacts
          Configuration:
            S3Bucket:
              Ref: SourceBucket
            S3ObjectKey:
              Ref: SourceObjectKey
          RunOrder: 1
      - Name: Deploy
        Actions:
        - InputArtifacts:
          - Name: !Ref SourceOutputArtifacts
          Name: Deploy
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Version: '1'
            Provider: CodeDeploy
          OutputArtifacts: []
          Configuration:
            ApplicationName:
              Ref: CodeDeployApplication
            DeploymentGroupName:
              Ref: CodeDeployDeploymentGroup
          RunOrder: 1
      ArtifactStore:
        Type: S3
        Location:
          Ref: Artifactbucket
Outputs:
  CodeDeployURL:
    Value:
      Fn::Join:
      - ''
      - - https://console.aws.amazon.com/codedeploy/home?region=
        - Ref: AWS::Region
        - "#/deployments/"
    Description: CodeDeploy URL
  CodePipelineURL:
    Value:
      Fn::Join:
      - ''
      - - https://console.aws.amazon.com/codepipeline/home?region=
        - Ref: AWS::Region
        - "#/view/"
        - Ref: CodePipelineStack
    Description: CodePipeline URL
    
    
    
    
    
    
    
    
    
    		######################## Parameter######################
    
# Key				                      Value						                              Resolved value
# ApplicationName			            Prod-Server-React-Deployment					            -
# Artifactbucket			            codepipeline-ap-south-1-637795064357				      -
# CodePipelineName			          SP-Prod-Pipeline-React					                  -
# CodePipelineSNSarn			        arn:aws:sns:ap-south-1:013297583948:Pipeline-Notifications		-
# ComputePlatform			            Server							                              -
# DeployConfiguration			        CodeDeployDefault.AllAtOnce					              -
# DeploymentGroupName		          Prod-Server-React-Deploymentgroup				          -
# EnvironmentName			            Prod							                                -
# ServerName			                PROD-EC2-Autoscale-Primary					              -
# SourceBucket			              salespanda-gitlab-s3						                  -
# SourceObjectKey			            react-ui/Prod-Server/code.zip					            -
# SourceOutputArtifacts			      sourceartifactprodreact						                -
# TagKey				                  Name							                                -
# TagValue				                PROD-EC2-Autoscale-Primary					              -
# TriggerName			                Prod-Server-React-Trigger					                -

