apiVersion: v1
data:
  cwagentconfig.json: |
    {
      "agent": {
        "region": "ap-south-1"
      },
      "logs": {
        "metrics_collected": {
          "kubernetes": {
            "cluster_name": "pace20-prod-in",
            "metrics_collection_interval": 60
          }
        },
        "force_flush_interval": 5
      }
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"cwagentconfig.json":"{\n  \"agent\": {\n    \"region\": \"ap-south-1\"\n  },\n  \"logs\": {\n    \"metrics_collected\": {\n      \"kubernetes\": {\n        \"cluster_name\": \"pace20-prod-in\",\n        \"metrics_collection_interval\": 60\n      }\n    },\n    \"force_flush_interval\": 5\n  }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"cwagentconfig","namespace":"amazon-cloudwatch"}}
  creationTimestamp: "2021-12-30T15:49:52Z"
  name: cwagentconfig
  namespace: amazon-cloudwatch
  resourceVersion: "20865818"
  uid: 24927431-059d-49d7-b80b-a7080ae4a89f